workingDir: ""
url: packages/rancher-monitoring/57.0.3/rancher-monitoring
version: 0.4.4
ignoreDependencies:
  - hardenedKubelet
  - hardenedNodeExporter
  - k3sServer
  - kube-state-metrics
  - kubeAdmControllerManager
  - kubeAdmProxy
  - kubeAdmScheduler
  - kubeAdmEtcd
  - prometheus-adapter
  - prometheus-node-exporter
  - rke2ControllerManager
  - rke2Etcd
  - rke2IngressNginx
  - rke2Proxy
  - rke2Scheduler
  - rkeControllerManager
  - rkeEtcd
  - rkeIngressNginx
  - rkeProxy
  - rkeScheduler
  - windowsExporter
replacePaths:
  - README.md
  - app-README.md
