url: oci://ghcr.io/kube-logging/helm-charts/logging-operator:5.4.0
version: 5.4.0-rancher.0
ignoreDependencies:
  - logging-operator-crds
  - telemetry-controller
additionalCharts:
  - workingDir: charts-crd
    crdOptions:
      templateDirectory: crd-template
      crdDirectory: templates
      addCRDValidationToMainChart: true
doNotRelease: false
